version: '3.7'

services:
  api:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://pg_user:pg_password@db/docker
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pg_user
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_DB=docker
    ports:
      - "5432:5432"

volumes:
  postgres_data:
