version: '3.7'

services:
  api:
    build: ./app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./app/postgres_scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=docker
    ports:
      - "5432:5432"

volumes:
  postgres_data:
