# pull official base image
FROM python:3.8.1-alpine

# set work directory
WORKDIR /usr/src/app

# Gather ENV
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_DB
ARG AUTH_SECRET

ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_HOST ${POSTGRES_HOST}
ENV POSTGRES_DB ${POSTGRES_DB}
ENV AUTH_SECRET ${AUTH_SECRET}

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN set -eux \
    && apk add --no-cache --virtual .build-deps build-base \
        libressl-dev libffi-dev gcc musl-dev python3-dev \
        postgresql-dev curl \
    && pip install --upgrade pip setuptools wheel \
    && rm -rf /root/.cache/pip

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy using poetry.lock* in case it doesn't exist yet
COPY ./pyproject.toml ./poetry.lock* /usr/src/app/

# Install deps
RUN poetry install --no-root --no-dev

# copy project
COPY  . /usr/src/app/

# Run
CMD uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
